# Generated by Django 6.1.1 on 2026-09-26 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                blank=True, related_name="dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
